name: Validate Pull Request

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, synchronize, labeled, unlabeled]

jobs:
  validate:
    name: Validate PR Description and linked issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Check PR description
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GHP_TOKEN }}
          script: |
            const { validatePr } = require('./.github/workflows/scripts/validate_pr.js');
            await validatePr({ github, context, core });

      - name: Check PR labels
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GHP_TOKEN }}
          script: |
            const script = require('./.github/workflows/scripts/check_labels.js');
            await script({ github, context, core });
