name: Validate PR Description and linked issue

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, synchronize, labeled, unlabeled]

jobs:
  call-workflow:
    uses: TurboNext/.github/.github/workflows/reusable_validate_pr.yml@main
    secrets: inherit
